image: maven:latest

stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: -s .m2/settings.xml --batch-mode -Drevision=.$CI_PIPELINE_IID
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
  paths:
    - .m2/repository/
    - target/

maven-build:
  stage: build
  script:
    - mvn -B $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
  only:
    - master

maven-deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master