main: nl.parrotlync.parrotpluginmanager.spigot.ParrotPluginManager
name: ParrotPluginManager
version: 1.1
description: Plugin manager for plugins made by ParrotLync
author: ParrotLync
commands:
  ppm:
    usage: /ppm help
    description: Basic ParrotPluginManager command
permissions:
  ppm.check:
    default: op
    description: Permission to use PPM commands
  ppm.staff:
    default: op
    description: Permission to receive PPM messages