main: nl.parrotlync.parrotpluginmanager.spigot.ParrotPluginManager
name: ${artifactId}
version: ${version}
description: ${description}
author: ParrotLync
commands:
  ppm:
    usage: /ppm help
    description: Basic ParrotPluginManager command
permissions:
  ppm.check:
    default: op
    description: Permission to use PPM commands
  ppm.staff:
    default: op
    description: Permission to receive PPM messages